"""campo idade pessoa2

Revision ID: 4e5ac4536b32
Revises: 574014e8f55c
Create Date: 2025-09-24 12:21:26.616643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e5ac4536b32'
down_revision: Union[str, Sequence[str], None] = '574014e8f55c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pessoa2_temp')
    op.add_column('pessoa2', sa.Column('idade', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pessoa2', 'idade')
    op.create_table('pessoa2_temp',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), nullable=False),
    sa.Column('senha', sa.INTEGER(), nullable=False),
    sa.Column('idade', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
