"""alteração do tamanho do campo email na tabela pessoa 1 Revision ID: d74c237bc232 Revises: 4e5ac4536b32 Create Date: 2025-09-25 16:46:50.085578 """ 
from typing import Sequence, Union 
from alembic import op 
import sqlalchemy as sa 
# revision identifiers, used by Alembic. 
revision: str = 'd74c237bc232' 
down_revision: Union[str, Sequence[str], None] = '4e5ac4536b32' 
branch_labels: Union[str, Sequence[str], None] = None 
depends_on: Union[str, Sequence[str], None] = None 
def upgrade() -> None:
    """Upgrade schema.""" 
    # ### commands auto generated by Alembic - please adjust! ### 
    
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.alter_column(
                        'email', 
                        existing_type=sa.VARCHAR(length=50), 
                        type_=sa.String(length=100), 
                        existing_nullable=False) 
    # ### end Alembic commands ### 
def downgrade() -> None: 
    """Downgrade schema.""" 
    # ### commands auto generated by Alembic - please adjust! ### 
    with op.batch_alter_table('pessoa', schema=None) as batch_op:

        batch_op.alter_column(
                            'email',
                            existing_type=sa.String(length=100),
                            type_=sa.VARCHAR(length=50), 
                            existing_nullable=False
                            ) 
        # ### end Alembic commands ###